import http from 'node:http'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), 'dist')
const artists = ['Beyond','S.H.E','G.E.M.邓紫棋','周杰伦','孙燕姿','五月天','林俊杰','张学友','梁静茹','蔡依林','王菲','田馥甄'].map((title,index)=>({ratingKey:String(index+1),type:'artist',title,summary:`${title} 的音乐跨越不同阶段，作品兼具鲜明旋律与个人表达。这里汇集已入库的专辑、热门曲目和完整媒体资料。`,tags:{genre:index%2?['华语流行']:['摇滚']},thumb:index%4?'mock':'',thumbUrl:index%4?'/visuals/fallback-cover-vinyl.svg':'',art:index%3?'mock-bg':'',artUrl:index%3?'/visuals/fallback-artist.svg':''}))
const albums = ['女生宿舍','范特西','七里香','我要我们在一起','寓言','叶惠美','逆光','勇气','十一月的萧邦','盖世英雄','神的孩子都在跳舞','八度空间'].map((title,index)=>({ratingKey:String(index+30),type:'album',title,parentTitle:artists[index%artists.length].title,parentRatingKey:artists[index%artists.length].ratingKey,year:2000+index,thumb:index%5?'mock':'',thumbUrl:index%5?'/visuals/fallback-cover-vinyl.svg':'',artUrl:'/visuals/fallback-artist.svg'}))
const tracks = Array.from({length:30},(_,index)=>({ratingKey:String(100+index),title:['恋人未满','晴天','勇气','海阔天空','光年之外'][index%5],grandparentTitle:artists[index%artists.length].title,parentTitle:albums[index%albums.length].title,duration:215000+index*1400}))
const jobs = [
  {id:8,kind:'scrape_artists',title:'更新歌手海报、背景与中文简介',status:'running',progress:68,message:'正在处理 梁静茹 (72/105)',created_at:new Date(Date.now()-180000).toISOString()},
  {id:7,kind:'fill_lyrics',title:'补齐缺失时间轴歌词',status:'completed',progress:100,message:'完成',created_at:new Date(Date.now()-3600000).toISOString()},
  {id:6,kind:'fill_album_covers',title:'补齐缺失专辑封面',status:'completed',progress:100,message:'完成',created_at:new Date(Date.now()-7200000).toISOString()},
  {id:5,kind:'download',title:'下载 周杰伦 - 晴天',status:'waiting_confirm',progress:95,message:'等待确认入库',result:{preview:{incomingPath:'/music/_incoming/周杰伦-晴天.mp3',targetPath:'/music/周杰伦/叶惠美/03 - 晴天.mp3',title:'晴天',artist:'周杰伦',album:'叶惠美',quality:'320k',conflictAdjusted:false}},created_at:new Date(Date.now()-9000000).toISOString()},
]
const source={id:'demo-source',name:'[独家音源]',displayName:'[独家音源]',sourceType:'file',status:'resolve_ok',enabled:true,accessGranted:true,catalogReady:true,downloadCapable:true,searchOk:true,resolveOk:true,detectedFormat:'lx-event',compatibility:'full',successRate:100,supportedPlatforms:['kw','kg','tx','wy','mg','local'],supportedQualities:['128k','320k','flac','flac24bit'],lastTestAt:new Date(Date.now()-900000).toISOString(),lastErrorMessage:null,metadata:{author:'洛雪科技',version:'4'}}
const searchResults=tracks.slice(0,8).map((t,i)=>({sourceId:source.id,sourceName:source.displayName,platform:'tx',trackId:String(i),id:String(i),title:t.title,artist:t.grandparentTitle,album:t.parentTitle,duration:240+i*3,coverUrl:'',cover:'',qualities:['128k','320k','flac'],musicInfo:{source:'tx',id:`tx_${i}`,meta:{songId:String(i)}}}))
const localFiles=tracks.slice(0,14).map((t,i)=>({id:`file-${i}`,path:`/music/${t.grandparentTitle}/${t.parentTitle}/${String(i+1).padStart(2,'0')} - ${t.title}.flac`,filename:`${String(i+1).padStart(2,'0')} - ${t.title}.flac`,title:t.title,artist:t.grandparentTitle,album:t.parentTitle,album_artist:t.grandparentTitle,year:'2003',track_number:String(i+1),disc_number:'1',genre:'华语流行',format:'FLAC',size:32_000_000,has_cover:i%3!==0,has_lrc:i%4!==0,plex_matched:i%5!==0,path_rule_ok:true}))
const pendingDownloads=[{jobId:5,title:'晴天',artist:'周杰伦',album:'叶惠美',quality:'320k',source:'[独家音源]',downloadPath:'/music/_incoming/周杰伦-晴天.mp3',targetPath:'/music/周杰伦/叶惠美/03 - 晴天.mp3',tagStatus:'已写入',coverStatus:'已保存',lyricStatus:'已保存',conflict:false,preview:jobs[3].result.preview}]
const plexSettings={enabled:true,name:'极空间 Plex',serverUrl:'http://127.0.0.1:32400',externalUrl:'http://127.0.0.1:32400',token:'',hasToken:true,selectedLibraryKeys:'all',lastConnectedAt:new Date(Date.now()-600000).toISOString(),lastSyncAt:new Date(Date.now()-1200000).toISOString(),libraries:[{key:'26',title:'音乐',type:'artist',enabled:true},{key:'27',title:'演唱会音乐',type:'artist',enabled:true}],syncedLibraryCount:2}
const users=[{id:'admin',username:'admin',displayName:'管理员',role:'admin',enabled:true,createdAt:new Date(Date.now()-86400000).toISOString(),updatedAt:new Date().toISOString(),lastLoginAt:new Date(Date.now()-300000).toISOString()}]
const json = (res,data,status=200)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(data))}
const port = Number(process.env.PORT || 4174)
http.createServer((req,res)=>{
  const url=new URL(req.url,'http://localhost')
  if(url.pathname.startsWith('/api/')){
    if(url.pathname==='/api/auth/status')return json(res,{authenticated:!String(req.headers.referer||'').includes('login=1'),user:users[0]})
    if(url.pathname==='/api/auth/login')return json(res,{ok:true})
    if(url.pathname==='/api/users'&&req.method==='POST')return json(res,{...users[0],id:'demo-user',username:'demo'})
    if(url.pathname==='/api/users')return json(res,{items:users})
    if(/^\/api\/users\/[^/]+\/password$/.test(url.pathname))return json(res,{ok:true})
    if(/^\/api\/users\/[^/]+$/.test(url.pathname)&&['PATCH','DELETE'].includes(req.method))return json(res,req.method==='DELETE'?{ok:true}:users[0])
    if(url.pathname==='/api/dashboard')return json(res,{artists:105,artistPosters:104,artistBackgrounds:35,chineseBios:102,albums:302,albumCovers:299,tracks:1439,localLyrics:1427,missingLyrics:12,musicRoot:'/music',plexConnected:true,heroImages:[{type:'plex_artist_background',title:'S.H.E',subtitle:'Plex 歌手背景',imageUrl:'/visuals/fallback-artist.svg',coverUrl:'/visuals/fallback-cover-vinyl.svg'},{type:'local_artist_background',title:'周杰伦',subtitle:'本地 artist-background',imageUrl:'/visuals/fallback-player.svg',coverUrl:'/visuals/fallback-cover-vinyl.svg'}]})
    if(url.pathname==='/api/jobs')return json(res,jobs)
    if(/^\/api\/jobs\/\d+$/.test(url.pathname)){const job=jobs.find(item=>String(item.id)===url.pathname.split('/').pop())||jobs[0];return json(res,{...job,logs:[{id:'1',level:'info',message:'任务开始执行。',created_at:job.created_at},{id:'2',level:job.status==='waiting_confirm'?'info':'success',message:job.status==='waiting_confirm'?'下载完成，等待用户确认入库预览。':'任务全部步骤执行完成。',created_at:new Date().toISOString()}]})}
    if(url.pathname==='/api/sources')return json(res,[source])
    if(url.pathname===`/api/sources/${source.id}/test-search`)return json(res,{ok:true,source_id:source.id,platform:'tx',count:searchResults.length,results:searchResults})
    if(url.pathname===`/api/sources/${source.id}/test-resolve`)return json(res,{ok:true,message:'下载地址解析可用。',source})
    if(url.pathname===`/api/sources/${source.id}/inspect`)return json(res,{ok:true,source_id:source.id,detected_format:'lx-event',top_level_keys:['lx.EVENT_NAMES','lx.on','lx.send','lx.request'],methods:{search:false,resolve:true,lyric:true,cover:true},compatibility:'full',catalog_search_adapter:true,supported_platforms:source.supportedPlatforms,supported_qualities:source.supportedQualities,message:'已识别为洛雪事件协议源；搜索由音屿目录适配器提供，下载地址由该源解析。'})
    if(url.pathname===`/api/sources/${source.id}/logs`)return json(res,[{id:'s1',level:'success',action:'validate',message:'隔离加载校验通过；请继续测试搜索和下载地址解析。',created_at:new Date(Date.now()-1800000).toISOString()},{id:'s2',level:'success',action:'test_resolve',message:'320k 下载地址解析与音频探测成功。',created_at:new Date(Date.now()-900000).toISOString()}])
    if(url.pathname==='/api/downloads/pending')return json(res,{items:pendingDownloads,total:pendingDownloads.length})
    if(url.pathname==='/api/downloads/device-token')return json(res,{ok:true,filename:'周杰伦 - 晴天.mp3',downloadUrl:'/api/mock-audio/download',contentType:'audio/mpeg'})
    if(url.pathname==='/api/downloads/batch-confirm'||url.pathname==='/api/downloads/batch-cancel')return json(res,{items:[]})
    if(url.pathname.startsWith('/api/player/local/')&&!url.pathname.endsWith('/stream')&&!url.pathname.endsWith('/lyrics')&&!url.pathname.endsWith('/cover')){const id=url.pathname.split('/').pop();const item=localFiles.find(file=>file.id===id)||localFiles[0];return json(res,{source:'local_file',id:item.id,title:item.title,artist:item.artist,album:item.album,file:item.path,streamUrl:`/api/player/local/${item.id}/stream`,lyricsUrl:`/api/player/local/${item.id}/lyrics`,qualities:['original']})}
    if(url.pathname.endsWith('/lyrics'))return json(res,{lyrics:'[00:00.00]暂无歌词\\n[00:10.00]让散落的音乐回到自己的岛屿',format:'lrc'})
    if(url.pathname.startsWith('/api/local/files/')&&url.pathname.endsWith('/lyrics'))return json(res,{lyrics:'[00:00.00]暂无歌词\\n[00:10.00]让散落的音乐回到自己的岛屿',format:'lrc'})
    if(url.pathname.startsWith('/api/local/files/')&&url.pathname.endsWith('/cover')){res.writeHead(302,{location:'/icons/icon-192.png'});return res.end()}
    if(url.pathname.startsWith('/api/local/files/')&&url.pathname.endsWith('/stream')){res.writeHead(204,{'accept-ranges':'bytes'});return res.end()}
    if(url.pathname.startsWith('/api/player/plex/')&&!url.pathname.endsWith('/stream')){const key=url.pathname.split('/')[4];const item=tracks.find(track=>track.ratingKey===key)||tracks[0];return json(res,{source:'plex_item',ratingKey:key,title:item.title,artist:item.grandparentTitle,album:item.parentTitle,file:`/music/${item.grandparentTitle}/${item.parentTitle}/${item.title}.flac`,streamUrl:`/api/player/plex/${key}/stream`,qualities:['original','320k','256k','192k','128k']})}
    if(url.pathname==='/api/player/source-preview')return json(res,{source:'source_preview',title:'晴天',artist:'周杰伦',album:'叶惠美',streamUrl:'/api/mock-audio/preview',quality:'128k'})
    if(url.pathname==='/api/profile')return json(res,{username:'admin',displayName:'管理员',avatarUrl:'',theme:'dark',defaultSource:'tx',defaultQuality:'320k'})
    if(url.pathname==='/api/profile/avatar')return json(res,{ok:true,profile:{username:'admin',displayName:'管理员',avatarUrl:'/icons/icon-192.png',theme:'dark',defaultSource:'tx',defaultQuality:'320k'}})
    if(url.pathname==='/api/logs/summary')return json(res,{updatedAt:new Date().toISOString(),jobLogs:[{id:'jl1',level:'success',job_title:'扫描本地曲库',message:'扫描完成。',created_at:new Date().toISOString()}],sourceLogs:[{id:'sl1',level:'success',source_name:'[独家音源]',action:'test_resolve',message:'地址解析成功。',created_at:new Date().toISOString()}],operations:[{id:'op1',status:'success',action:'tag_write',target_id:'file-1',created_at:new Date().toISOString()}]})
    if(url.pathname==='/api/settings/plex'&&req.method==='POST')return json(res,{ok:true,settings:plexSettings})
    if(url.pathname==='/api/settings/plex')return json(res,plexSettings)
    if(url.pathname==='/api/plex/test')return json(res,{ok:true,message:'Plex 连接成功，已识别到 2 个音乐资料库。',identity:{friendlyName:'Mock Plex'},libraryCount:2,libraries:plexSettings.libraries,connectedAt:new Date().toISOString()})
    if(url.pathname==='/api/plex/libraries')return json(res,{items:plexSettings.libraries})
    if(url.pathname==='/api/plex/sync')return json(res,{id:11,kind:'plex_sync',title:'同步 Plex 音乐资料库',status:'queued',progress:0,created_at:new Date().toISOString()})
    if(/^\/api\/plex\/items\/[^/]+\/playback$/.test(url.pathname)){const key=url.pathname.split('/')[4];const item=tracks.find(track=>track.ratingKey===key)||tracks[0];return json(res,{ratingKey:key,title:item.title,artist:item.grandparentTitle,album:item.parentTitle,duration:item.duration,coverUrl:'/visuals/fallback-cover-vinyl.svg',artistBackgroundUrl:'/visuals/fallback-artist.svg',directPlayUrl:`/api/player/plex/${key}/stream?bitrate=original`,transcodeUrls:{original:`/api/player/plex/${key}/stream?bitrate=original`,'320k':`/api/player/plex/${key}/stream?bitrate=320k`},lyrics:'[00:00.00]模拟 Plex 歌词\\n[00:10.00]底部播放器现在会动了',file:`/music/${item.grandparentTitle}/${item.parentTitle}/${item.title}.flac`,openPlexUrl:'http://127.0.0.1:32400/web'})}
    if(/^\/api\/player\/plex\/[^/]+\/stream$/.test(url.pathname)){res.writeHead(204,{'accept-ranges':'bytes'});return res.end()}
    if(url.pathname==='/api/settings')return json(res,{appName:'SongLib Amp｜音屿',version:'1.0.0-rc.5',plex:plexSettings,plexServerName:plexSettings.name,musicRoot:'/music',plexUrl:plexSettings.serverUrl,externalPlexUrl:plexSettings.externalUrl,plexSection:'26',downloadDir:'_downloads',downloadTempDir:'/music/_downloads',incomingDir:'/music/_incoming',manualDownloadDir:'/downloads',trashDir:'/music/.trash',lyricRule:'同名 .lrc',coverRule:'专辑目录 cover.jpg + 音频内嵌封面',scrapeRules:{defaultMode:'missing',writeCover:true,writeLyrics:true,refreshPlex:true,skipExistingCover:true,skipExistingLyrics:true},namingTemplates:{album:'/{artist}/{album} ({year})/{trackNumber} - {title}.{ext}',multiDisc:'/{artist}/{album} ({year})/{discNumber}{trackNumber} - {title}.{ext}',compilation:'/Various Artists/{album} ({year})/{trackNumber} - {artist} - {title}.{ext}',unknown:'/{artist}/Unknown Album/{title}.{ext}'},excludeDirs:['/music/_incoming','/music/_downloads','/music/.trash','/music/@eaDir','/music/#recycle'],player:{},user:{username:'admin',role:'admin',permissions:['manage_users','manage_library','manage_sources'],fontSize:'standard',defaultSource:'tx',defaultQuality:'320k'},maxDownloadMb:500,sourceMaxSizeMb:2,fnosMusic:{configured:false,serverUrl:'http://127.0.0.1:5666/music',authMode:'password',accountLabel:''}})
    if(/^\/api\/library\/artists\/[^/]+$/.test(url.pathname)){const item=artists.find(value=>value.ratingKey===url.pathname.split('/').at(-1))||artists[0];const related=albums.filter(value=>value.parentRatingKey===item.ratingKey);return json(res,{artist:item,albums:related,popularTracks:tracks.slice(0,8).map(value=>({...value,grandparentTitle:item.title})),trackCount:24,albumCount:related.length})}
    if(/^\/api\/library\/albums\/[^/]+$/.test(url.pathname)){const item=albums.find(value=>value.ratingKey===url.pathname.split('/').at(-1))||albums[0];const artist=artists.find(value=>value.ratingKey===item.parentRatingKey)||artists[0];const related=tracks.slice(0,10).map((value,index)=>({...value,index:index+1,parentTitle:item.title,grandparentTitle:artist.title}));return json(res,{album:item,artist,tracks:related,trackCount:related.length,duration:related.reduce((sum,value)=>sum+value.duration,0)})}
    if(url.pathname==='/api/library/artists')return json(res,{items:artists,total:artists.length,page:1,pageSize:200})
    if(url.pathname==='/api/library/albums')return json(res,{items:albums,total:albums.length,page:1,pageSize:200})
    if(url.pathname==='/api/library/tracks')return json(res,{items:tracks,total:tracks.length,page:1,pageSize:200})
    if(url.pathname==='/api/local/files')return json(res,{items:localFiles,total:localFiles.length,stats:{total:1439,missing_cover:14,missing_lyrics:12,missing_artist:2,missing_album:3,bad_path:9,plex_unmatched:6}})
    if(url.pathname==='/api/local/categories')return json(res,{summary:[{id:'tracks',label:'歌曲',count:1439,note:'首歌曲'},{id:'artists',label:'艺人',count:105,note:'位艺人'},{id:'albums',label:'专辑',count:306,note:'张专辑'},{id:'genres',label:'流派',count:14,note:'种流派'},{id:'folders',label:'文件夹',count:107,note:'个顶层目录'},{id:'lossless',label:'无损',count:720,note:'首高规格'}],groups:{genre:[{id:'华语流行',name:'华语流行',count:880,search:'华语流行'},{id:'摇滚',name:'摇滚',count:120,search:'摇滚'}],artist:artists.slice(0,8).map(a=>({id:a.title,name:a.title,count:12,search:a.title})),album:albums.slice(0,8).map(a=>({id:a.title,name:a.title,count:10,search:a.title})),folder:artists.slice(0,8).map(a=>({id:a.title,name:a.title,count:12,search:a.title})),format:[{id:'FLAC',name:'FLAC',count:900,search:'.flac'},{id:'MP3',name:'MP3',count:539,search:'.mp3'}],quality:[{id:'无损',name:'无损 / Hi-Res',count:900},{id:'标准',name:'标准音质',count:539}],year:[{id:'2003',name:'2003',count:120,search:'2003'}],scene:[{id:'影视原声',name:'影视原声',count:80,search:'原声'}],missing:[{id:'cover',name:'缺封面',count:14,missing:'cover'},{id:'lyrics',name:'缺歌词',count:12,missing:'lyrics'}]}})
    if(url.pathname==='/api/discovery/playlists')return json(res,{source:'netease-hottags',updatedAt:new Date().toISOString(),platforms:['网易云音乐','QQ 音乐','酷狗音乐'],categories:['热门','华语','流行','粤语','影视原声','经典','摇滚','民谣','电子','轻音乐','怀旧','治愈'].map((name,index)=>({id:`cat-${index}`,platform:index%3===0?'QQ 音乐':index%3===1?'网易云音乐':'酷狗音乐',name,count:10000-index*300,url:'https://music.163.com/'}))})
    if(url.pathname==='/api/local/operations')return json(res,[{id:'op1',action:'tag_write',target_id:'file-1',rollbackable:1,created_at:new Date(Date.now()-3600000).toISOString()}])
    if(url.pathname==='/api/catalog/search')return json(res,tracks.slice(0,8).map((t,i)=>({platform:'tx',id:String(i),title:t.title,artist:t.grandparentTitle,album:t.parentTitle,duration:240+i*3,cover:'',qualities:['128k','320k','flac'],musicInfo:{}})))
    return json(res,{ok:true})
  }
  let file=path.join(root,url.pathname==='/'?'index.html':url.pathname)
  if(!fs.existsSync(file)||fs.statSync(file).isDirectory())file=path.join(root,'index.html')
  const ext=path.extname(file);const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'}
  res.writeHead(200,{'content-type':`${types[ext]||'application/octet-stream'}; charset=utf-8`});fs.createReadStream(file).pipe(res)
}).listen(port,'127.0.0.1',()=>console.log(`mock UI http://127.0.0.1:${port}`))
